--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2
-- Dumped by pg_dump version 16.2

-- Started on 2026-09-25 12:55:55


--
-- TOC entry 4968 (class 0 OID 152775)
-- Dependencies: 280
-- Data for Name: opsi_ref; Type: TABLE DATA; Schema: public; Owner: postgres
--
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (280, 'Perhitungan nilai deviasi antara 0 s.d 4,99%', 10, 120, '', '', '', NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (281, 'Perhitungan nilai deviasi antara 5% s.d. 8%', 7, 120, '', '', '', NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (282, 'Perhitungan nilai deviasi lebih dari 8%.', 5, 120, '', '', '', NULL);



INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (283, 'KPPN melakukan upaya nyata meminimalisasi deviasi RPD, seperti surat pemberitahuan, rekap monitoring realisasi anggaran, atau bimbingan/konsultasi kepada Satker, disertai dokumen pendukung yang jelas.', 10, 121, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (284, 'Tidak terdapat bukti atau keterangan yang menunjukkan upaya KPPN dalam meminimalisasi deviasi RPD.', 0, 121, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (285, 'Tidak ditemukan penyimpangan atau ketidaksesuaian terhadap prosedur dalam SOP Penerbitan SP2D.', 10, 122, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (286, 'Ditemukan ketidaksesuaian terhadap prosedur kerja sesuai SOP Penerbitan SP2D.', 0, 122, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (287, 'Terdapat persetujuan tagihan dilakukan lebih dari 30 menit sampai dengan paling lama 1 jam sejak ADK SPM diproses dalam SPAN', 10, 123, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (288, 'Terdapat persetujuan tagihan dilakukan > 1 jam tanpa disertai Berita Acara Penyelesaian Keterlambatan.', 0, 123, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (289, 'Hasil perhitungan menunjukkan angka ≤ 3%.', 10, 124, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (290, 'Hasil perhitungan menunjukkan angka antara 3%–5%.', 7, 124, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (291, 'Hasil perhitungan menunjukkan angka > 5%.', 0, 124, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (292, 'Tidak ditemukan ketidaksesuaian terhadap prosedur dalam SOP Penerbitan SP2B BLU.', 10, 125, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (293, 'Ditemukan ketidaksesuaian terhadap prosedur dalam SOP Penerbitan SP2B BLU.', 0, 125, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (294, 'Tidak ditemukan ketidaksesuaian dalam pelaksanaan SOP Penerbitan MPHL-BJS.', 10, 126, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (295, 'Ditemukan ketidaksesuaian dalam pelaksanaan SOP Penerbitan MPHL-BJS.', 0, 126, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (296, 'KPPN melakukan pendaftaran, perubahan, dan penonaktifan data supplier sesuai dengan SOP.', 10, 127, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (297, 'Ditemukan ketidaksesuaian dalam proses pendaftaran, perubahan, dan penonaktifan data supplier sesuai dengan SOP.', 0, 127, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (298, 'Seluruh data pegawai dan supplier telah dinonaktifkan sesuai dengan penerbitan SKPP.', 10, 128, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (299, 'Terdapat data pegawai dan/atau supplier yang masih aktif setelah penerbitan SKPP.', 0, 128, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (300, 'Seluruh data kontrak dan perubahan kontrak memiliki dokumen pendukung yang lengkap dan sesuai ketentuan.', 10, 129, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (301, 'Tidak terdapat kelengkapan dokumen pendukung pada pendaftaran atau perubahan data kontrak.', 0, 129, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (302, 'Tren penggunaan KKP meningkat dalam satu semester selama periode pembinaan.', 10, 130, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (303, 'Tren penggunaan KKP fluktuatif dalam satu semester selama periode pembinaan.', 7, 130, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (304, 'Tren penggunaan KKP menurun dalam satu semester selama periode pembinaan.', 5, 130, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (305, 'Tren penggunaan CMS meningkat dalam satu semester selama periode pembinaan.', 10, 131, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (306, 'Tren penggunaan CMS fluktuatif dalam satu semester selama periode pembinaan.', 7, 131, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (307, 'Tren penggunaan CMS menurun dalam satu semester selama periode pembinaan.', 5, 131, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (308, 'Seluruh sisa UP/TUP telah disetor sebelum batas akhir tahun anggaran sebelumnya. (SMT 1)', 10, 132, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (309, 'Terdapat sisa UP/TUP yang disetor melewati batas akhir tahun anggaran sebelumnya. (SMT 1)', 0, 132, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (310, 'sisa UP/TUP yang belum disetor telah diselesaikan pada Semester I tahun berjalan; atau tidak terdapat keterlambatan penyetoran. (SMT 2)', 10, 132, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (311, 'Terdapat sisa UP/TUP tahun sebelumnya disetor melewati periode pembinaan Semester I. (SMT 2)', 0, 132, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (312, 'KPPN menerbitkan seluruh surat pemberitahuan kepada satker yang tidak mengajukan penggantian UP dalam waktu 2 bulan sejak SP2D-UP terbit.', 10, 133, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (313, 'KPPN tidak menerbitkan surat pemberitahuan penggantian UP kepada satker yang tidak mengajukan penggantian UP dalam 2 bulan sejak SP2D-UP terbit.', 0, 133, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (314, 'Pembukaan dan penutupan rekening Satker dilakukan sesuai dengan ketentuan yang berlaku dan didukung dokumen persyaratan yang lengkap.', 10, 134, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (315, 'Pembukaan dan penutupan rekening Satker tidak sesuai ketentuan dan/atau tidak dilengkapi dokumen persyaratan yang lengkap.', 0, 134, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (316, 'Terdapat tindak lanjut yang lengkap dan didukung bukti yang memadai (misalnya surat pemberitahuan, klarifikasi kepada satker, atau dokumen koreksi).', 10, 135, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (317, 'Tidak terdapat upaya tindak lanjut atas kesalahan data penerimaan negara.', 0, 135, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (318, 'KPPN melaksanakan verifikasi LPJ Bendahara sesuai ketentuan SOP dengan seluruh dokumen pendukung lengkap.', 10, 136, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (319, 'KPPN tidak melaksanakan verifikasi LPJ Bendahara, atau verifikasi dilakukan namun tidak sesuai ketentuan SOP dan disertai dokumen pendukung yang tidak lengkap.', 0, 136, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (320, 'Seluruh LPJ Bendahara disampaikan ke KPPN paling lambat tanggal 10 setiap bulan.', 10, 137, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (321, 'Terdapat LPJ Bendahara disampaikan ke KPPN pada tanggal 11–15 setiap bulan.', 5, 137, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (322, 'Terdapat LPJ Bendahara disampaikan ke KPPN lebih dari tanggal 15 setiap bulan.', 0, 137, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (323, 'KPPN menindaklanjuti seluruh to do list kualitas data laporan keuangan dengan bukti pembinaan atau klarifikasi yang memadai', 10, 138, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (324, 'KPPN menindaklanjuti sebagian to do list kualitas data laporan keuangan dengan bukti pembinaan atau klarifikasi yang memadai.', 7, 138, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (325, 'KPPN tidak menindaklanjuti to do list kualitas data laporan keuangan yang tercatat pada Aplikasi MyIntress.', 0, 138, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (326, 'Tidak terdapat anomali, atau seluruh anomali telah ditindaklanjuti sehingga tidak muncul kembali sampai batas waktu analisis.', 10, 139, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (327, 'Anomali telah ditindaklanjuti oleh KPPN, tetapi belum diselesaikan oleh satker.', 8, 139, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (328, 'Anomali ditindaklanjuti oleh KPPN setelah batas waktu analisis tetapi masih dalam bulan berikutnya.', 5, 139, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (329, 'Tidak ada tindak lanjut, atau tindak lanjut dilakukan oleh KPPN lebih dari satu bulan dari akhir bulan terjadinya anomali.', 0, 139, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (330, 'KPPN menerbitkan Berita Acara Peminjaman User SPAN/SAKTI bagi pejabat atau pegawai yang berhalangan (Plh/cuti) sesuai ketentuan.', 10, 140, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (331, 'KPPN tidak menerbitkan Berita Acara Peminjaman User SPAN/SAKTI ketika terdapat pejabat atau pegawai user SPAN/SAKTI yang berhalangan.', 0, 140, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (332, 'Seluruh sampel ditindaklanjuti dan dilengkapi dokumen sesuai ketentuan.', 10, 141, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (333, 'Seluruh sampel ditindaklanjuti tetapi dokumen tidak lengkap.', 0, 141, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (334, 'Seluruh sampling permohonan pendaftaran/ perubahan nomor telepon untuk keperluan OTP SAKTI telah ditindaklanjuti sesuai prosedur dan disertai dokumen persyaratan lengkap.', 10, 142, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (335, 'Seluruh sampling permohonan pendaftaran/ perubahan nomor telepon untuk keperluan OTP SAKTI telah ditindaklanjuti namun tidak disertai dokumen persyaratan lengkap.', 0, 142, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (336, 'Terdapat SK/Nota Dinas penunjukan PIC TIK tahun berjalan; seluruh perangkat aktif telah join domain dengan penamaan sesuai ketentuan; dan tersedia Formulir Penguatan Keamanan Informasi untuk seluruh sampling', 10, 143, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (337, 'Tidak terdapat SK/Nota Dinas PIC; terdapat perangkat yang belum join domain atau penamaannya tidak sesuai; atau formulir keamanan tidak tersedia.', 0, 143, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (338, 'Persentase realisasi sesuai ketentuan dengan deviasi ≤ 15%.', 10, 144, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (339, 'Persentase realisasi mendekati ketentuan dengan deviasi >15% s.d. 25%.', 5, 144, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (340, 'Deviasi realisasi terhadap ketentuan lebih dari 25%.', 0, 144, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (341, 'Pencocokan data dilakukan 100% terhadap seluruh data debitur dalam SIKP-UMi sebelum akhir periode triwulan.', 10, 145, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (342, 'Kegiatan pencocokan data oleh KPPN dilakukan 50% ≤ x < 100% terhadap data debitur yang muncul dalam SIKP-UMi sebelum akhir periode triwulan.', 5, 145, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (343, 'Kegiatan pencocokan data oleh KPPN berhasil dilakukan kurang dari 50% terhadap data debitur yang muncul dalam SIKP-UMi sebelum periode triwulan berkenaan berakhir.', 0, 145, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (344, 'KPPN melakukan analisis menggunakan metode analisis tertentu, dengan dukungan data valid, serta menghasilkan rekomendasi yang implementatif dan relevan dengan isu yang dibahas.', 10, 146, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (345, 'KPPN melakukan analisis deskriptif sederhana berbasis data yang valid, serta menyampaikan rekomendasi implementatif yang sesuai dengan konteks permasalahan.', 5, 146, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (346, 'KPPN tidak melakukan analisis permasalahan atau tidak memberikan rekomendasi atas isu pelaksanaan anggaran yang dibahas.', 0, 146, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (347, 'KPPN melakukan analisis secara komprehensif, sekurang-kurangnya memuat permasalahan utama, akar masalah, serta alternatif solusi/rekomendasi, serta menyampaikan rekomendasi yang bersifat implementatif dan selaras dengan permasalahan yang dibahas.', 10, 147, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (348, 'KPPN melakukan analisis permasalahan secara sederhana dan tidak memenuhi salah satu unsur minimal (permasalahan utama atau akar masalah), serta menyampaikan rekomendasi yang kurang implementatif dan/atau tidak sepenuhnya menjawab permasalahan dalam laporan monev TKD.', 5, 147, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (349, 'KPPN tidak menyusun analisis permasalahan dan tidak memberikan rekomendasi atas isu penyaluran TKD.', 0, 147, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (350, 'Persentase tindak lanjut analisis > 80% atau tidak ada data anomali dan laporan semesteran disampaikan tepat waktu.', 10, 148, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (351, 'Persentase tindak lanjut analisis 60% < x ≤ 80% atau laporan disampaikan tidak tepat waktu.', 7, 148, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (352, 'Persentase tindak lanjut ? 60% atau laporan tidak disampaikan.', 0, 148, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (353, 'KPPN mengamplifikasi informasi kebijakan keuangan negara di sosial medianya, paling sedikit 4 kali setiap bulan', 10, 149, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (354, 'KPPN mengamplifikasi informasi kebijakan keuangan negara di sosial medianya, kurang dari 4 kali setiap bulan', 5, 149, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (355, 'KPPN tidak pernah mengamplifikasi informasi kebijakan keuangan negara di sosial medianya setiap bulan', 0, 149, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (356, 'KPPN melakukan sosialisasi dan langkah-langkah percepatan konversi level sertifikasi kompetensi pejabat perbendaharaan.', 10, 150, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (357, 'KPPN melakukan pemberitahuan atas konversi level sertifikasi kompetensi pejabat perbendaharaan namun tidak melakukan kegiatan pendukung untuk percepatan konversi level sertifikasi kompetensi pejabat perbendaharaan (e.g. pembekalan tematik).', 5, 150, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (358, 'KPPN tidak melakukan pemberitahuan atas konversi level sertifikasi kompetensi pejabat perbendaharaan.', 0, 150, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (359, 'Hasil perhitungan menunjukkan persentase pejabat tersertifikasi ≤ 90%.', 10, 151, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (360, 'Hasil perhitungan menunjukkan persentase pejabat tersertifikasi antara 71%–89%.', 5, 151, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (361, 'Hasil perhitungan menunjukkan persentase pejabat tersertifikasi ≤ 70%.', 0, 151, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (362, 'KPPN telah menyelesaikan monev dan menindaklanjuti hasil monev dengan memadai', 10, 152, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (363, 'KPPN telah menyelesaikan monev namun belum menindaklanjuti hasil monev dengan memadai', 5, 152, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (364, 'KPPN belum menyelesaikan monitoring dan evaluasi', 0, 152, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (365, 'KPPN melaksanakan FGD/Sharing Session terkait CGA minimal 1 kali setiap triwulan dengan bukti dukung yang memadai', 10, 153, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (366, 'KPPN melaksanakan FGD/Sharing Session terkait CGA sebanyak 1 kali dalam 1 semester dengan bukti dukung yang memadai.', 5, 153, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (367, 'KPPN tidak melaksanakan FGD/ Sharing Session terkait CGA.', 0, 153, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (368, 'KPPN melaksanakan Sosialisasi/Bimtek CGA minimal 1 kali setiap triwulan dengan bukti dukung yang memadai.', 10, 154, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (369, 'KPPN melaksanakan Sosialisasi/Bimtek CGA sebanyak 1 kali dalam 1 semester dengan bukti dukung yang memadai.', 5, 154, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (370, 'KPPN tidak melaksanakan Sosialisasi/ Bimtek CGA', 0, 154, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (371, 'KPPN melakukan kegiatan asistensi minimal 1 kali setiap triwulan dengan bukti dukung yang memadai.', 10, 155, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (372, 'KPPN melakukan kegiatan asistensi sebanyak 1 kali dalam 1 semester dengan bukti dukung yang memadai.', 5, 155, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (373, 'KPPN tidak melakukan kegiatan asistensi', 0, 155, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (374, 'KPPN menjawab seluruh pertanyaan Satker melalui HAI CSO dengan tepat waktu (≤ 3 hari kerja).', 10, 156, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (375, 'KPPN menjawab seluruh pertanyaan Satker melalui HAI CSO dalam 4–5 hari kerja.', 7, 156, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (376, 'KPPN menjawab seluruh pertanyaan Satker melalui HAI CSO lebih dari 5 hari kerja.', 0, 156, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (377, 'KPPN melakukan kegiatan Monev terhadap satker minimal 1 kali setiap triwulan, disertai bukti dukung kegiatan yang memadai.', 10, 157, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (378, 'KPPN melakukan kegiatan Monev terhadap satker minimal 1 kali dalam 1 semester, disertai bukti dukung kegiatan yang memadai.', 5, 157, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (379, 'KPPN tidak melakukan kegiatan Monev terhadap satker.', 0, 157, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (380, 'KPPN menyampaikan seluruh dokumen hasil Monev dan tindak lanjutnya secara lengkap, terukur, dan didukung bukti yang memadai.', 10, 158, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (381, 'KPPN menyampaikan laporan hasil Monev, namun belum terdapat bukti upaya tindak lanjut atau rekomendasi perbaikan yang jelas.', 5, 158, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (382, 'KPPN tidak melaksanakan kegiatan Monev.', 0, 158, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (383, 'KPPN menyelenggarakan atau terlibat dalam FGD/Sharing Session minimal 1 kali setiap triwulan dengan bukti dukung yang memadai.', 10, 159, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (384, 'KPPN menyelenggarakan atau terlibat dalam FGD/Sharing Session sebanyak 1 kali dalam 1 semester dengan bukti dukung yang memadai.', 5, 159, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (385, 'KPPN tidak melaksanakan atau terlibat dalam kegiatan FGD/Sharing Session terkait LGA', 0, 159, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (386, 'KPPN melaksanakan kegiatan Sosialisasi/ Bimtek minimal 1 kali setiap triwulan disertai bukti dukung yang lengkap dan memadai', 10, 160, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (387, 'KPPN melaksanakan kegiatan Sosialisasi/ Bimtek sebanyak 1 kali dalam 1 semester disertai bukti dukung yang lengkap dan memadai.', 5, 160, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (388, 'KPPN tidak melaksanakan kegiatan Sosialisasi/Bimtek terkait LGA selama periode penilaian', 0, 160, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (389, 'KPPN melakukan upaya/tindak lanjut atas permasalahan terkait dengan Penyaluran TKD disertai dengan bukti dukung yang memadai.', 10, 161, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (390, 'KPPN melakukan upaya/tindak lanjut atas sebagian permasalahan terkait dengan Penyaluran TKD disertai dengan bukti dukung yang memadai;', 5, 161, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (391, 'KPPN tidak melakukan upaya tindak lanjut atas permasalahan TKD yang disampaikan oleh Pemda.', 0, 161, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (392, 'KPPN melaksanakan kegiatan monev kepada Pemda minimal 1 kali setiap triwulan dan dilengkapi dengan bukti dukung kegiatan yang lengkap dan memadai.', 10, 162, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (393, 'KPPN melakukan monev kepada Pemda minimal 1 kali dalam 1 semester disertai dokumen bukti kegiatan yang memadai', 5, 162, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (394, 'KPPN tidak melakukan monev kepada Pemda.', 0, 162, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (395, 'KPPN menyampaikan seluruh dokumen hasil monev dan tindak lanjutnya dengan lengkap dan memadai.', 10, 163, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (396, 'KPPN menyampaikan hasil monev namun tidak terdapat upaya tindak lanjut yang terdokumentasi', 5, 163, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (397, 'KPPN tidak melakukan kegiatan monev terhadap Pemerintah Daerah', 0, 163, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (398, 'KPPN menyelenggarakan atau terlibat dalam kegiatan FGD/Sharing Session minimal 1 kali setiap triwulan, dilengkapi bukti dukung yang memadai', 10, 164, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (399, 'KPPN menyelenggarakan atau terlibat dalam kegiatan FGD/Sharing Session sebanyak 1 kali dalam 1 semester, dilengkapi bukti dukung yang memadai', 5, 164, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (400, 'KPPN tidak melakukan kegiatan FGD/Sharing Session terkait Special Mission', 0, 164, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (401, 'KPPN melakukan Sosialisasi/Bimtek minimal 1 kali setiap triwulan dilampiri dengan bukti dukung yang memadai', 10, 165, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (402, 'KPPN melakukan Sosialisasi/Bimtek sebanyak 1 kali dalam 1 semester dilampiri dengan bukti dukung yang memadai', 5, 165, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (403, 'KPPN tidak melakukan Sosialisasi/ Bimtek', 0, 165, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (404, 'KPPN melakukan kegiatan monev kepada BLU minimal 1 kali setiap triwulan dengan bukti dukung kegiatan yang memadai.', 10, 166, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (405, 'KPPN melakukan kegiatan monev kepada BLU minimal 1 kali dalam 1 semester dengan bukti dukung kegiatan yang memadai.', 5, 166, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (406, 'KPPN tidak melakukan kegiatan monev kepada BLU selama periode penilaian.', 0, 166, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (407, 'KPPN melakukan monev pembiayaan UMi minimal 1 kali selama 1 triwulan disertai dokumen bukti kegiatan yang memadai.', 10, 167, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (408, 'KPPN melakukan monev pembiayaan UMi minimal 1 kali dalam 1 semester disertai dokumen bukti kegiatan yang memadai.', 5, 167, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (409, 'KPPN melakukan monev pembiayaan UMi minimal 1 kali dalam 1 semester disertai dokumen bukti kegiatan yang memadai.', 0, 167, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (410, 'KPPN memperoleh 90% s.d. 100% laporan keuangan BUMD sesuai hasil identifikasi oleh Kanwil DJPb.', 10, 168, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (411, 'KPPN memperoleh 50% s.d. 89% laporan keuangan BUMD sesuai hasil identifikasi oleh Kanwil DJPb.', 5, 168, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (412, 'KPPN memperoleh kurang dari 50% laporan keuangan BUMD sesuai hasil
identifikasi oleh Kanwil DJPb.', 0, 168, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (413, 'KPPN telah melakukan translasi dan unggah pada sistem informasi sebesar 90% s.d. 100% dari total laporan keuangan BUMD yang diperoleh.', 10, 169, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (414, 'KPPN telah melakukan translasi dan unggah pada sistem informasi sebesar 50% s.d. 89% dari total laporan keuangan BUMD yang diperoleh.', 5, 169, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (415, 'KPPN telah melakukan translasi dan unggah pada sistem informasi kurang dari 50% dari total laporan keuangan BUMD yang diperoleh.', 0, 169, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (416, 'KPPN dapat menyampaikan seluruh dokumen hasil monev dan tindak lanjutnya dengan lengkap dan memadai', 10, 170, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (417, 'KPPN menyampaikan hasil monev namun tidak terdapat upaya tindak lanjut', 5, 170, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (418, 'KPPN tidak melakukan monev', 0, 170, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (419, 'KPPN telah melakukan perhitungan NKO dengan benar dan sesuai ketentuan yang berlaku.', 10, 171, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (420, 'Ditemukan kesalahan dalam perhitungan NKO oleh KPPN.', 0, 171, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (421, '75%-100% pegawai KPPN telah mengunggah dokumen kinerja di Aplikasi INTENSE.', 10, 172, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (422, '50% ≤ x < 75% pegawai KPPN telah mengunggah dokumen kinerja di Aplikasi INTENSE.', 5, 172, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (423, 'Kurang dari 50% pegawai KPPN telah mengunggah dokumen kinerja di Aplikasi INTENSE.', 0, 172, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (424, 'Evaluasi capaian kinerja internal dilaksanakan minimal 1 kali setiap bulan, dengan laporan dan dokumentasi lengkap', 10, 173, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (425, 'Evaluasi capaian kinerja internal dilaksanakan minimal 1 kali setiap triwulan, dengan laporan dan dokumentasi lengkap', 5, 173, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (426, 'KPPN tidak melaksanakan evaluasi capaian kinerja internal', 0, 173, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (427, 'KPPN telah menyusun Dokumen Induk (Pedoman Mutu, Konteks Organisasi, Kebijakan Mutu), dengan ketentuan: a. Pedoman Mutu dan Kebijakan Mutu dilakukan revisi apabila terdapat kebutuhan untuk dilakukan penyesuaian (misalnya jika terdapat perubahan proses bisnis, struktur tata kelola organisasi, lokasi/alamat kantor dll) b. Konteks Organisasi telah dilakukan revisi setelah penandatanganan Sasaran Kinerja.', 10, 174, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (428, 'KPPN menyusun Dokumen Induk namun terdapat ketidaksesuaian pada satu atau lebih atas unsur Dokumen Induk dengan ketentuan dan/atau dengan kondisi terkini.', 5, 174, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (429, 'Tidak terdapat dokumentasi atas Dokumen Induk di KPPN.', 0, 174, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (430, 'KPPN melaksanakan pengujian kepatuhan minimal 1 tahun sekali dan menyusun laporan hasil pengujian kepatuhan beserta dokumen pendukungnya (ST, Proker pengujian dll) sesuai ketentuan dalam KEP-151', 10, 175, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (431, 'KPPN melaksanakan pengujian kepatuhan minimal 1 tahun sekali namun tidak menyusun laporan hasil pengujian kepatuhan dan/atau tidak terdapat dokumen pendukung yang lengkap (ST, Proker pengujian dll) sesuai ketentuan dalam KEP-151', 5, 175, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (432, 'KPPN tidak melaksanakan pengujian kepatuhan.', 0, 175, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (433, 'KPPN melakukan pengisian volume kerja sebelum batas waktu yang ditetapkan dan menyampaikan laporan ke Sekretariat DJPb.', 10, 176, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (434, 'KPPN melakukan pengisian volume kerja melewati batas waktu yang ditetapkan.', 5, 176, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (435, 'KPPN tidak melakukan pengisian volume kerja.', 0, 176, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (436, 'Rata-rata nilai SKM KPPN pada Aplikasi PETARAJA berada pada kategori Sangat Baik (>=90).', 10, 177, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (437, 'Rata-rata nilai SKM KPPN berada pada kategori Baik (80–89).', 5, 177, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (438, 'Rata-rata nilai SKM KPPN berada pada kategori Cukup atau Kurang (<80).', 0, 177, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (439, 'Tidak ditemukan kesalahan prosedur dalam pelaksanaan layanan kepegawaian dan diselesaikan dengan tepat waktu', 10, 178, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (440, 'Ditemukan kesalahan prosedur dalam pelaksanaan layanan kepegawaian kurang dari 30%.', 7, 178, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (441, 'Ditemukan kesalahan prosedur dalam pelaksanaan layanan kepegawaian antara 30%–50%.', 5, 178, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (442, 'Ditemukan kesalahan prosedur dalam pelaksanaan layanan kepegawaian lebih dari 50%.', 0, 178, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (443, 'Tingkat kelengkapan dokumen dalam aplikasi kepegawaian atas seluruh pegawai, 80% telah diisi lengkap', 10, 179, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (444, 'Tingkat kelengkapan dokumen dalam aplikasi kepegawaian yang menjadi sampling, antara 50% s.d. < 80% telah diisi lengkap', 7, 179, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (445, 'Tingkat kelengkapan dokumen dalam aplikasi kepegawaian yang menjadi sampling, <50% telah diisi lengkap', 5, 179, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (446, 'Tingkat kelengkapan dokumen dalam aplikasi kepegawaian yang menjadi sampling, tidak diisi lengkap secara keseluruhan', 0, 179, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (447, '86%–100% pegawai telah memenuhi standar kompetensi minimal sesuai jabatannya.', 10, 180, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (448, '50%–85% pegawai telah memenuhi standar kompetensi minimal sesuai jabatannya.', 5, 180, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (449, 'Kurang dari 50% pegawai memenuhi standar kompetensi minimal.', 0, 180, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (450, 'Data pada Aplikasi SMART DJA telah terisi setiap bulan secara lengkap dan sesuai jadwal pelaporan yang ditetapkan', 10, 181, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (451, 'Data pada Aplikasi SMART DJA tidak terisi lengkap dan/atau tidak dilakukan secara periodik sesuai ketentuan.', 0, 181, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (452, 'KPPN melakukan pengisian data evaluasi anggaran setiap bulan secara lengkap sesuai jadwal pelaporan e-Monev Bappenas', 10, 182, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (453, 'KPPN tidak melakukan pengisian data evaluasi anggaran setiap bulan atau datanya tidak lengkap.', 0, 182, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (454, 'Pembayaran UM dan UL dilakukan sesuai ketentuan dan disertai dokumen pendukung yang lengkap.', 10, 183, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (455, 'Pembayaran UM dan UL tidak sesuai ketentuan dan/atau tidak disertai dokumen pendukung yang lengkap.', 0, 183, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (456, 'Pembayaran belanja barang dan/atau modal dilakukan sesuai ketentuan dan didukung dokumen lengkap.', 10, 184, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (457, 'Pembayaran belanja barang dan/atau modal tidak sesuai ketentuan dan/atau tidak disertai dokumen pendukung yang lengkap.', 0, 184, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (458, 'Seluruh perikatan oleh PPK telah dilaksanakan sesuai dengan ketentuan pengadaan barang/jasa pemerintah.', 10, 185, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (459, 'Ditemukan ketidaksesuaian terhadap ketentuan pengadaan barang/jasa pemerintah.', 0, 185, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (460, '80–100% dokumen pencairan anggaran telah diarsipkan secara digital (cetakan aplikasi dan/atau hasil pemindaian)', 10, 186, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (461, '50–79% dokumen pencairan anggaran telah diarsipkan secara digital (cetakan aplikasi dan/atau hasil pemindaian).', 5, 186, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (462, 'Kurang dari 50% dokumen pencairan anggaran telah diarsipkan secara digital.', 0, 186, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (463, '80–100% kegiatan pengamanan dan pemeliharaan BMN telah dilaksanakan sesuai pedoman.', 10, 187, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (464, '50–79% kegiatan pengamanan dan pemeliharaan BMN sesuai pedoman', 5, 187, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (465, 'Kurang dari 50% kegiatan pengamanan dan pemeliharaan BMN sesuai pedoman.', 0, 187, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (466, 'Total bobot kesesuaian standard >= 90', 10, 188, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (467, 'Total bobot kesesuaian standard 65-90', 7, 188, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (468, 'Total bobot kesesuaian standard 50-64', 5, 188, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (469, 'Total bobot kesesuaian standard < 50', 0, 188, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (470, 'Total bobot kesesuaian standard > 90', 10, 189, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (471, 'Ketika total bobot kesesuaian standard 65-90', 7, 189, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (472, 'Ketika total bobot kesesuaian standard 50-64', 5, 189, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (473, 'Ketika total bobot kesesuaian standard < 50', 0, 189, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (474, 'Ketika total bobot kesesuaian standard 91 – 100', 10, 190, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (475, 'Ketika total bobot kesesuaian standard 65-90 dan/atau 101-125', 7, 190, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (476, 'Ketika total bobot kesesuaian standard 50-64 dan/atau 126-140', 5, 190, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (477, 'Ketika total bobot kesesuaian standard < 50 dan/atau > 140', 0, 190, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (478, 'Ketika total bobot kesesuaian standard >=90', 10, 191, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (479, 'Ketika total bobot kesesuaian standard 65-90', 7, 191, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (480, 'Ketika total bobot kesesuaian standard 50-64', 5, 191, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (481, 'Ketika total bobot kesesuaian standard < 50', 0, 191, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (482, 'KPPN melaksanakan identifikasi, pemantauan, dan evaluasi risiko secara triwulanan dengan laporan lengkap dan sesuai ketentuan.', 10, 192, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (483, 'KPPN melaksanakan identifikasi, pemantauan, dan evaluasi risiko secara triwulanan, namun laporan belum lengkap atau belum sepenuhnya sesuai ketentuan.', 5, 192, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (484, 'KPPN tidak melaksanakan atau tidak melaporkan kegiatan manajemen risiko secara triwulanan sesuai ketentuan.', 0, 192, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (485, 'Tidak terdapat temuan administratif maupun substantif dari hasil pemeriksaan aparat pemeriksa.', 10, 193, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (486, 'Terdapat temuan administratif atau substantif, namun telah ditindaklanjuti secara tepat waktu sesuai rekomendasi pemeriksa.', 8, 193, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (487, 'Terdapat temuan administratif atau substantif, namun telah ditindaklanjuti sesuai rekomendasi pemeriksa.', 5, 193, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (488, 'Terdapat temuan administratif atau substantif yang belum atau tidak ditindaklanjuti sesuai rekomendasi pemeriksa.', 0, 193, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (489, 'KPPN memiliki petugas pengelola pengaduan, mekanisme penanganan yang jelas, serta dokumentasi pengelolaan pengaduan yang lengkap dan tertata.', 10, 194, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (490, 'Seluruh pengaduan ditindaklanjuti secara tuntas, disertai bukti/dokumen hasil tindak lanjut yang lengkap, namun laporan pengaduan tidak disampaikan tepat waktu sesuai ketentuan.', 5, 194, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (491, 'KPPN belum menetapkan petugas dan/atau belum memiliki mekanisme pengelolaan pengaduan yang jelas.', 0, 194, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (492, 'Seluruh pengaduan ditindaklanjuti secara tuntas dan tepat waktu, disertai bukti/dokumen hasil tindak lanjut yang lengkap.', 10, 195, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (493, 'Tidak terdapat tindak lanjut atas pengaduan yang diterima dan/atau tidak ada bukti laporan tindak lanjut yang dapat ditunjukkan.', 0, 195, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (494, 'KPPN melakukan pembaruan secara rutin dan konsisten setiap bulan pada website dan media sosial resmi KPPN.', 10, 196, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (495, 'KPPN melakukan pembaruan secara rutin kurang dari satu bulan sekali pada salah satu kanal resmi (website atau media sosial).', 5, 196, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (496, 'KPPN tidak melakukan pembaruan konten secara rutin dan/atau pembaruan dilakukan kurang dari satu kali per triwulan.', 0, 196, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (497, 'KPPN melaksanakan atau berpartisipasi aktif dalam kegiatan yang secara langsung memperkuat citra positif DJPb di masyarakat.', 10, 197, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (498, 'KPPN tidak memiliki keterlibatan dalam kegiatan kemasyarakatan dan/atau tidak terdapat upaya yang menampilkan peran dan citra positif DJPb di masyarakat.', 0, 197, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (499, 'KPPN melaksanakan atau berpartisipasi aktif dalam program employee advocacy sebesar 90%-100% jumlah pegawai.', 10, 198, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (500, 'KPPN melaksanakan atau berpartisipasi aktif dalam program employee advocacy minimal 60%-89% jumlah pegawai.', 8, 198, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (501, 'KPPN melaksanakan atau berpartisipasi aktif dalam program employee advocacy minimal 40%-59% jumlah pegawai.', 7, 198, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (502, 'KPPN tidak memiliki keterlibatan dalam program employee advocacy.', 0, 198, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (503, 'KPPN telah menetapkan SK Inovasi disertai proposal inovasi pada tahun berkenaan dan inovasi telah terdaftar pada Katalog Inovasi Satu Kemenkeu.', 10, 199, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (504, 'KPPN telah menetapkan SK Inovasi dan proposal inovasi pada tahun berkenaan namun belum terdaftar pada Katalog Inovasi Satu Kemenkeu.', 5, 199, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (505, 'KPPN tidak melakukan penetapan SK Inovasi', 0, 199, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (506, 'KPPN secara aktif mengelola inovasi melalui kegiatan pemanfaatan, pemantauan, evaluasi, dan pengembangan dengan bukti dukung yang lengkap.', 10, 200, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (507, 'KPPN memanfaatkan atau menggunakan inovasi yang dimiliki tanpa kegiatan pengembangan atau evaluasi lanjutan.', 5, 200, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (508, 'Tidak terdapat kegiatan pengelolaan inovasi (inovasi tidak dimanfaatkan atau tidak digunakan).', 0, 200, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (509, 'KPPN telah melakukan sosialisasi atau promosi inovasi kepada pihak eksternal, dan inovasi tersebut telah direplikasi oleh pihak lain dengan bukti dukung memadai.', 10, 201, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (510, 'KPPN melakukan sosialisasi atau promosi inovasi kepada pihak eksternal disertai bukti dukung yang memadai namun belum direplikasi.', 5, 201, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (511, 'Tidak terdapat upaya sosialisasi atau promosi atas inovasi yang dimiliki.', 0, 201, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (512, 'KPPN mempertahankan prestasi sebelumnya dan/atau meraih prestasi baru dengan bukti dukung berupa naskah dinas atau sertifikat penghargaan.', 10, 202, NULL, NULL, NULL, NULL);
INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (513, 'Tidak terdapat prestasi yang dipertahankan maupun prestasi baru yang diraih oleh KPPN.', 0, 202, NULL, NULL, NULL, NULL);

INSERT INTO public.opsi_ref (id, title, value, checklist_id, positive_fallback, negative_fallback, rekomendasi, deleted) VALUES (514, 'Seluruh persetujuan tagihan dilakukan ≤30 menit sejak ADK SPM diproses dalam SPAN', 15, 123, NULL, NULL, NULL, NULL);
-- Completed on 2026-09-25 12:55:55

--
-- PostgreSQL database dump complete
--

